# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceCOLORIDA.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow")
        MainWindow2.resize(800, 660)
        MainWindow2.setMinimumSize(QtCore.QSize(800, 660))
        MainWindow2.setStyleSheet("background-color: #6397EB;\n"
"border:none")
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setStyleSheet("*{\n"
"border:none\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(238, 238, 236);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, -1, 0, 9)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.Main = QtWidgets.QFrame(self.centralwidget)
        self.Main.setMinimumSize(QtCore.QSize(0, 0))
        self.Main.setStyleSheet("")
        self.Main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main.setObjectName("Main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Main)
        self.verticalLayout.setContentsMargins(0, 2, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.Main)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ABTN = QtWidgets.QPushButton(self.frame)
        self.ABTN.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/Menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ABTN.setIcon(icon)
        self.ABTN.setIconSize(QtCore.QSize(32, 32))
        self.ABTN.setObjectName("ABTN")
        self.horizontalLayout_3.addWidget(self.ABTN, 0, QtCore.Qt.AlignLeft)
        self.TopFrame = QtWidgets.QLabel(self.frame)
        self.TopFrame.setObjectName("TopFrame")
        self.horizontalLayout_3.addWidget(self.TopFrame)
        self.verticalLayout.addWidget(self.frame)
        self.MainFrame = QtWidgets.QFrame(self.Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainFrame.sizePolicy().hasHeightForWidth())
        self.MainFrame.setSizePolicy(sizePolicy)
        self.MainFrame.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.MainFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.MainFrame)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.PgHome = QtWidgets.QWidget()
        self.PgHome.setObjectName("PgHome")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.PgHome)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.PgHome)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Icons/Logo.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.stackedWidget.addWidget(self.PgHome)
        self.PgConta = QtWidgets.QWidget()
        self.PgConta.setStyleSheet("")
        self.PgConta.setObjectName("PgConta")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.PgConta)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_8 = QtWidgets.QFrame(self.PgConta)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_10 = QtWidgets.QLabel(self.frame_11)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("Icons/Perfilfoto.png"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_25.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(self.frame_11)
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_25.addWidget(self.label_9)
        self.verticalLayout_24.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_12)
        self.tabWidget.setStyleSheet("color: rgb(0, 0, 0)")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.Labelnome = QtWidgets.QLabel(self.tab_3)
        self.Labelnome.setStyleSheet("")
        self.Labelnome.setObjectName("Labelnome")
        self.verticalLayout_34.addWidget(self.Labelnome)
        self.Labelemail = QtWidgets.QLabel(self.tab_3)
        self.Labelemail.setStyleSheet("")
        self.Labelemail.setObjectName("Labelemail")
        self.verticalLayout_34.addWidget(self.Labelemail)
        self.Labeltelefone = QtWidgets.QLabel(self.tab_3)
        self.Labeltelefone.setStyleSheet("color: rgb(0, 0, 0);")
        self.Labeltelefone.setObjectName("Labeltelefone")
        self.verticalLayout_34.addWidget(self.Labeltelefone)
        self.mudarsenha = QtWidgets.QPushButton(self.tab_3)
        self.mudarsenha.setMinimumSize(QtCore.QSize(0, 30))
        self.mudarsenha.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(239, 41, 41);\n"
"   border-top-left-radus:15px;\n"
"   color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius:15px;\n"
"}\n"
"")
        self.mudarsenha.setObjectName("mudarsenha")
        self.verticalLayout_34.addWidget(self.mudarsenha)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.Labelpeso = QtWidgets.QLabel(self.tab_4)
        self.Labelpeso.setStyleSheet("")
        self.Labelpeso.setObjectName("Labelpeso")
        self.verticalLayout_31.addWidget(self.Labelpeso)
        self.LabelAltura = QtWidgets.QLabel(self.tab_4)
        self.LabelAltura.setStyleSheet("")
        self.LabelAltura.setObjectName("LabelAltura")
        self.verticalLayout_31.addWidget(self.LabelAltura)
        self.LabelImc = QtWidgets.QLabel(self.tab_4)
        self.LabelImc.setStyleSheet("")
        self.LabelImc.setObjectName("LabelImc")
        self.verticalLayout_31.addWidget(self.LabelImc)
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_31.addWidget(self.label_22)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_33.addWidget(self.tabWidget)
        self.verticalLayout_24.addWidget(self.frame_12)
        self.horizontalLayout_6.addWidget(self.frame_8)
        self.frame_10 = QtWidgets.QFrame(self.PgConta)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.frame_13 = QtWidgets.QFrame(self.frame_10)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.frame_16 = QtWidgets.QFrame(self.frame_13)
        self.frame_16.setStyleSheet("background-color: #43ACB5;\n"
"border-radius:15px;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_editarUser = QtWidgets.QPushButton(self.frame_16)
        self.btn_editarUser.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_editarUser.setFont(font)
        self.btn_editarUser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_editarUser.setStyleSheet("\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(65, 156, 204);\n"
"   border-top-left-radus:15px\n"
"}")
        self.btn_editarUser.setObjectName("btn_editarUser")
        self.horizontalLayout_7.addWidget(self.btn_editarUser)
        self.btn_Alterconta = QtWidgets.QPushButton(self.frame_16)
        self.btn_Alterconta.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_Alterconta.setFont(font)
        self.btn_Alterconta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Alterconta.setStyleSheet("\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(65, 156, 204);\n"
"   border-top-left-radus:15px\n"
"}")
        self.btn_Alterconta.setObjectName("btn_Alterconta")
        self.horizontalLayout_7.addWidget(self.btn_Alterconta)
        self.btn_adicionarConta = QtWidgets.QPushButton(self.frame_16)
        self.btn_adicionarConta.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_adicionarConta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_adicionarConta.setStyleSheet("\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(65, 156, 204);\n"
"   border-top-left-radus:15px\n"
"}")
        self.btn_adicionarConta.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/Upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_adicionarConta.setIcon(icon1)
        self.btn_adicionarConta.setObjectName("btn_adicionarConta")
        self.horizontalLayout_7.addWidget(self.btn_adicionarConta)
        self.verticalLayout_30.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_13)
        self.frame_17.setStyleSheet("")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Progressototal = QtWidgets.QProgressBar(self.frame_17)
        self.Progressototal.setStyleSheet("")
        self.Progressototal.setProperty("value", 24)
        self.Progressototal.setObjectName("Progressototal")
        self.horizontalLayout_8.addWidget(self.Progressototal)
        self.label_18 = QtWidgets.QLabel(self.frame_17)
        self.label_18.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.verticalLayout_30.addWidget(self.frame_17)
        self.verticalLayout_29.addWidget(self.frame_13)
        self.frame_15 = QtWidgets.QFrame(self.frame_10)
        self.frame_15.setStyleSheet("background-color: #43ACB5;\n"
"border-radius:15px;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.relatorioconfig = QtWidgets.QListWidget(self.frame_15)
        self.relatorioconfig.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.relatorioconfig.setObjectName("relatorioconfig")
        self.verticalLayout_32.addWidget(self.relatorioconfig)
        self.verticalLayout_29.addWidget(self.frame_15)
        self.horizontalLayout_6.addWidget(self.frame_10)
        self.stackedWidget.addWidget(self.PgConta)
        self.PgLembretes = QtWidgets.QWidget()
        self.PgLembretes.setObjectName("PgLembretes")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.PgLembretes)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.FrameLembrete = QtWidgets.QFrame(self.PgLembretes)
        self.FrameLembrete.setStyleSheet("background-color: #43ACB5;\n"
"border-radius:15px;")
        self.FrameLembrete.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameLembrete.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameLembrete.setObjectName("FrameLembrete")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.FrameLembrete)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.FrameLembrete)
        self.dateTimeEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dateTimeEdit.setAutoFillBackground(False)
        self.dateTimeEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.dateTimeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout_9.addWidget(self.dateTimeEdit)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.FrameLembrete)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setTabletTracking(False)
        self.calendarWidget.setAcceptDrops(False)
        self.calendarWidget.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.calendarWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.ISOWeekNumbers)
        self.calendarWidget.setNavigationBarVisible(False)
        self.calendarWidget.setDateEditEnabled(False)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_9.addWidget(self.calendarWidget)
        self.verticalLayout_8.addWidget(self.FrameLembrete)
        self.stackedWidget.addWidget(self.PgLembretes)
        self.PgRelatorio = QtWidgets.QWidget()
        self.PgRelatorio.setObjectName("PgRelatorio")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.PgRelatorio)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_19 = QtWidgets.QFrame(self.PgRelatorio)
        self.frame_19.setStyleSheet("background-color: #43ACB5;\n"
"border-radius:15px;")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.tableView = QtWidgets.QTableView(self.frame_19)
        self.tableView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableView.setObjectName("tableView")
        self.verticalLayout_36.addWidget(self.tableView)
        self.verticalLayout_10.addWidget(self.frame_19)
        self.stackedWidget.addWidget(self.PgRelatorio)
        self.PgAlimentar = QtWidgets.QWidget()
        self.PgAlimentar.setObjectName("PgAlimentar")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.PgAlimentar)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.frame_20 = QtWidgets.QFrame(self.PgAlimentar)
        self.frame_20.setStyleSheet("background-color: #273C5E;\n"
"border-radius:15px;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.label_17 = QtWidgets.QLabel(self.frame_20)
        self.label_17.setMinimumSize(QtCore.QSize(0, 30))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_39.addWidget(self.label_17)
        self.frame_26 = QtWidgets.QFrame(self.frame_20)
        self.frame_26.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_26.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_26.setStyleSheet("background-color: #2D456B;\n"
"border-radius:15px;")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btvoltaralimento = QtWidgets.QPushButton(self.frame_26)
        self.btvoltaralimento.setMinimumSize(QtCore.QSize(0, 30))
        self.btvoltaralimento.setStyleSheet("QPushButton:hover{\n"
"    background-color: #324D78;\n"
"   border-top-left-radus:15px\n"
"}")
        self.btvoltaralimento.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/voltar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btvoltaralimento.setIcon(icon2)
        self.btvoltaralimento.setObjectName("btvoltaralimento")
        self.horizontalLayout_9.addWidget(self.btvoltaralimento)
        self.btselecionaralimento = QtWidgets.QPushButton(self.frame_26)
        self.btselecionaralimento.setMinimumSize(QtCore.QSize(0, 30))
        self.btselecionaralimento.setStyleSheet("QPushButton:hover{\n"
"    background-color: #324D78;\n"
"   border-top-left-radus:15px\n"
"}")
        self.btselecionaralimento.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/Editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btselecionaralimento.setIcon(icon3)
        self.btselecionaralimento.setObjectName("btselecionaralimento")
        self.horizontalLayout_9.addWidget(self.btselecionaralimento)
        self.btsalvaralimento = QtWidgets.QPushButton(self.frame_26)
        self.btsalvaralimento.setMinimumSize(QtCore.QSize(0, 30))
        self.btsalvaralimento.setStyleSheet("QPushButton:hover{\n"
"    background-color: #324D78;\n"
"   border-top-left-radus:15px\n"
"}")
        self.btsalvaralimento.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons/Salvar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btsalvaralimento.setIcon(icon4)
        self.btsalvaralimento.setObjectName("btsalvaralimento")
        self.horizontalLayout_9.addWidget(self.btsalvaralimento)
        self.verticalLayout_39.addWidget(self.frame_26)
        self.Menucomida = QtWidgets.QFrame(self.frame_20)
        self.Menucomida.setMinimumSize(QtCore.QSize(0, 0))
        self.Menucomida.setMaximumSize(QtCore.QSize(16777215, 0))
        self.Menucomida.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Menucomida.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Menucomida.setObjectName("Menucomida")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.Menucomida)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_22 = QtWidgets.QFrame(self.Menucomida)
        self.frame_22.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.label_19 = QtWidgets.QLabel(self.frame_22)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_47.addWidget(self.label_19)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_22)
        self.comboBox_4.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"border-color: rgb(136, 138, 133);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.verticalLayout_47.addWidget(self.comboBox_4)
        self.label_21 = QtWidgets.QLabel(self.frame_22)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_47.addWidget(self.label_21)
        self.comboBox_5 = QtWidgets.QComboBox(self.frame_22)
        self.comboBox_5.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"border-color: rgb(136, 138, 133);")
        self.comboBox_5.setObjectName("comboBox_5")
        self.verticalLayout_47.addWidget(self.comboBox_5)
        self.horizontalLayout_12.addWidget(self.frame_22)
        self.frame_28 = QtWidgets.QFrame(self.Menucomida)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.label_28 = QtWidgets.QLabel(self.frame_28)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_48.addWidget(self.label_28)
        self.Alimentocomentario = QtWidgets.QLineEdit(self.frame_28)
        self.Alimentocomentario.setMinimumSize(QtCore.QSize(0, 100))
        self.Alimentocomentario.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 255, 255);")
        self.Alimentocomentario.setObjectName("Alimentocomentario")
        self.verticalLayout_48.addWidget(self.Alimentocomentario)
        self.horizontalLayout_12.addWidget(self.frame_28)
        self.verticalLayout_39.addWidget(self.Menucomida)
        self.FrameMetrixDieta = QtWidgets.QFrame(self.frame_20)
        self.FrameMetrixDieta.setMinimumSize(QtCore.QSize(0, 0))
        self.FrameMetrixDieta.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 255, 255);")
        self.FrameMetrixDieta.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameMetrixDieta.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameMetrixDieta.setObjectName("FrameMetrixDieta")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.FrameMetrixDieta)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_35 = QtWidgets.QFrame(self.FrameMetrixDieta)
        self.frame_35.setStyleSheet("background-color: rgb(92, 53, 102);")
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_51 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.Alimento3 = QtWidgets.QLabel(self.frame_35)
        self.Alimento3.setText("")
        self.Alimento3.setObjectName("Alimento3")
        self.verticalLayout_51.addWidget(self.Alimento3)
        self.gridLayout_2.addWidget(self.frame_35, 0, 1, 1, 1)
        self.frame_29 = QtWidgets.QFrame(self.FrameMetrixDieta)
        self.frame_29.setStyleSheet("background-color: rgb(78, 154, 6);")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_50 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.Alimento1 = QtWidgets.QLabel(self.frame_29)
        self.Alimento1.setText("")
        self.Alimento1.setObjectName("Alimento1")
        self.verticalLayout_50.addWidget(self.Alimento1)
        self.gridLayout_2.addWidget(self.frame_29, 0, 0, 1, 1)
        self.frame_37 = QtWidgets.QFrame(self.FrameMetrixDieta)
        self.frame_37.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.verticalLayout_52 = QtWidgets.QVBoxLayout(self.frame_37)
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.Alimento2 = QtWidgets.QLabel(self.frame_37)
        self.Alimento2.setText("")
        self.Alimento2.setObjectName("Alimento2")
        self.verticalLayout_52.addWidget(self.Alimento2)
        self.gridLayout_2.addWidget(self.frame_37, 1, 0, 1, 1)
        self.frame_39 = QtWidgets.QFrame(self.FrameMetrixDieta)
        self.frame_39.setStyleSheet("background-color: rgb(206, 92, 0);")
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_55 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.Alimento6 = QtWidgets.QLabel(self.frame_39)
        self.Alimento6.setText("")
        self.Alimento6.setObjectName("Alimento6")
        self.verticalLayout_55.addWidget(self.Alimento6)
        self.gridLayout_2.addWidget(self.frame_39, 1, 2, 1, 1)
        self.frame_36 = QtWidgets.QFrame(self.FrameMetrixDieta)
        self.frame_36.setStyleSheet("background-color: rgb(164, 0, 0);")
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.verticalLayout_53 = QtWidgets.QVBoxLayout(self.frame_36)
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.Alimento4 = QtWidgets.QLabel(self.frame_36)
        self.Alimento4.setText("")
        self.Alimento4.setObjectName("Alimento4")
        self.verticalLayout_53.addWidget(self.Alimento4)
        self.gridLayout_2.addWidget(self.frame_36, 1, 1, 1, 1)
        self.frame_38 = QtWidgets.QFrame(self.FrameMetrixDieta)
        self.frame_38.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.verticalLayout_54 = QtWidgets.QVBoxLayout(self.frame_38)
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.Alimento5 = QtWidgets.QLabel(self.frame_38)
        self.Alimento5.setText("")
        self.Alimento5.setObjectName("Alimento5")
        self.verticalLayout_54.addWidget(self.Alimento5)
        self.gridLayout_2.addWidget(self.frame_38, 0, 2, 1, 1)
        self.verticalLayout_39.addWidget(self.FrameMetrixDieta)
        self.verticalLayout_37.addWidget(self.frame_20)
        self.stackedWidget.addWidget(self.PgAlimentar)
        self.PgChat = QtWidgets.QWidget()
        self.PgChat.setObjectName("PgChat")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.PgChat)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.frame_25 = QtWidgets.QFrame(self.PgChat)
        self.frame_25.setStyleSheet("background-color:#43ACB5;\n"
"border-radius:15px;")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.frame_18 = QtWidgets.QFrame(self.frame_25)
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_18.setStyleSheet("")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.Mensagem_Email = QtWidgets.QPushButton(self.frame_18)
        self.Mensagem_Email.setMinimumSize(QtCore.QSize(230, 50))
        self.Mensagem_Email.setStyleSheet("QPushButton{\n"
"    background-color: rgb(65, 156, 204);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(62, 113, 194);\n"
"   border-top-left-radus:15px\n"
"}")
        self.Mensagem_Email.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icons/Mensagens.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Mensagem_Email.setIcon(icon5)
        self.Mensagem_Email.setObjectName("Mensagem_Email")
        self.horizontalLayout_10.addWidget(self.Mensagem_Email)
        self.verticalLayout_43.addWidget(self.frame_18)
        self.frame_27 = QtWidgets.QFrame(self.frame_25)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_30 = QtWidgets.QFrame(self.frame_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_30.sizePolicy().hasHeightForWidth())
        self.frame_30.setSizePolicy(sizePolicy)
        self.frame_30.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.frame_31 = QtWidgets.QFrame(self.frame_30)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_25 = QtWidgets.QLabel(self.frame_31)
        self.label_25.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_25.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_15.addWidget(self.label_25)
        self.Email_da_Pessoa = QtWidgets.QLabel(self.frame_31)
        self.Email_da_Pessoa.setStyleSheet("color: rgb(0, 0, 0);")
        self.Email_da_Pessoa.setText("")
        self.Email_da_Pessoa.setAlignment(QtCore.Qt.AlignCenter)
        self.Email_da_Pessoa.setObjectName("Email_da_Pessoa")
        self.horizontalLayout_15.addWidget(self.Email_da_Pessoa)
        self.verticalLayout_49.addWidget(self.frame_31)
        self.frame_32 = QtWidgets.QFrame(self.frame_30)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_26 = QtWidgets.QLabel(self.frame_32)
        self.label_26.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_16.addWidget(self.label_26)
        self.Email_enviar = QtWidgets.QLineEdit(self.frame_32)
        self.Email_enviar.setStyleSheet("color: rgb(0, 0, 0);")
        self.Email_enviar.setObjectName("Email_enviar")
        self.horizontalLayout_16.addWidget(self.Email_enviar)
        self.verticalLayout_49.addWidget(self.frame_32)
        self.frame_33 = QtWidgets.QFrame(self.frame_30)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_27 = QtWidgets.QLabel(self.frame_33)
        self.label_27.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_17.addWidget(self.label_27)
        self.Email_assunto = QtWidgets.QLineEdit(self.frame_33)
        self.Email_assunto.setStyleSheet("color: rgb(0, 0, 0);")
        self.Email_assunto.setObjectName("Email_assunto")
        self.horizontalLayout_17.addWidget(self.Email_assunto)
        self.verticalLayout_49.addWidget(self.frame_33)
        self.frame_34 = QtWidgets.QFrame(self.frame_30)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_24 = QtWidgets.QLabel(self.frame_34)
        self.label_24.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_18.addWidget(self.label_24)
        self.Email_Mensagem = QtWidgets.QLineEdit(self.frame_34)
        self.Email_Mensagem.setObjectName("Email_Mensagem")
        self.horizontalLayout_18.addWidget(self.Email_Mensagem)
        self.verticalLayout_49.addWidget(self.frame_34)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_30)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(239, 41, 41);\n"
"   border-top-left-radus:15px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_49.addWidget(self.pushButton_2)
        self.horizontalLayout_13.addWidget(self.frame_30)
        self.Menu_Email = QtWidgets.QFrame(self.frame_27)
        self.Menu_Email.setMinimumSize(QtCore.QSize(0, 0))
        self.Menu_Email.setMaximumSize(QtCore.QSize(0, 16777215))
        self.Menu_Email.setStyleSheet("background-color: rgb(65, 156, 204);")
        self.Menu_Email.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Menu_Email.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Menu_Email.setObjectName("Menu_Email")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.Menu_Email)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.scrollArea_8 = QtWidgets.QScrollArea(self.Menu_Email)
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollArea_8.setObjectName("scrollArea_8")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 86, 377))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.Lista_de_emails = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.Lista_de_emails.setObjectName("Lista_de_emails")
        self.verticalLayout_44.addWidget(self.Lista_de_emails)
        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_14.addWidget(self.scrollArea_8)
        self.horizontalLayout_13.addWidget(self.Menu_Email)
        self.verticalLayout_43.addWidget(self.frame_27)
        self.verticalLayout_42.addWidget(self.frame_25)
        self.stackedWidget.addWidget(self.PgChat)
        self.PgTreino = QtWidgets.QWidget()
        self.PgTreino.setObjectName("PgTreino")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.PgTreino)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_2 = QtWidgets.QFrame(self.PgTreino)
        self.frame_2.setStyleSheet("background-color: #273C5E;\n"
"border-radius:15px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.btn_Anae = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Anae.sizePolicy().hasHeightForWidth())
        self.btn_Anae.setSizePolicy(sizePolicy)
        self.btn_Anae.setMinimumSize(QtCore.QSize(0, 100))
        self.btn_Anae.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_Anae.setFont(font)
        self.btn_Anae.setStyleSheet("QPushButton{\n"
"    \n"
"    \n"
"    \n"
"    background-image: url(Corrida.png);\n"
"    border-radius:15px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.btn_Anae.setIconSize(QtCore.QSize(0, 0))
        self.btn_Anae.setObjectName("btn_Anae")
        self.verticalLayout_13.addWidget(self.btn_Anae)
        self.btn_academia = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_academia.sizePolicy().hasHeightForWidth())
        self.btn_academia.setSizePolicy(sizePolicy)
        self.btn_academia.setMinimumSize(QtCore.QSize(0, 100))
        self.btn_academia.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_academia.setFont(font)
        self.btn_academia.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_academia.setStyleSheet("QPushButton{\n"
"  \n"
"    \n"
"    \n"
"    background-image: url(Academia.png);\n"
"border-radius:15px;\n"
"   color:rgb(255, 255, 255)\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Beta/APP Beta/Versão Final App/exercicio/d56b8d7c-e220-46f7-8acd-a595cc97eb29-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_academia.setIcon(icon6)
        self.btn_academia.setIconSize(QtCore.QSize(100, 100))
        self.btn_academia.setObjectName("btn_academia")
        self.verticalLayout_13.addWidget(self.btn_academia)
        self.btn_Alonga = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Alonga.sizePolicy().hasHeightForWidth())
        self.btn_Alonga.setSizePolicy(sizePolicy)
        self.btn_Alonga.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Alonga.setFont(font)
        self.btn_Alonga.setStyleSheet("QPushButton{\n"
"     \n"
"    \n"
"    \n"
"    \n"
"    background-image: url(Alongamento.png);\n"
"   border-radius:15px;\n"
"   color:rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Beta/APP Beta/Versão Final App/exercicio/5677e46d-070e-4d35-9074-5b6f17bb5b7a-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Alonga.setIcon(icon7)
        self.btn_Alonga.setIconSize(QtCore.QSize(100, 100))
        self.btn_Alonga.setObjectName("btn_Alonga")
        self.verticalLayout_13.addWidget(self.btn_Alonga)
        self.btn_casa = QtWidgets.QPushButton(self.frame_4)
        self.btn_casa.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_casa.setFont(font)
        self.btn_casa.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_casa.setAutoFillBackground(False)
        self.btn_casa.setStyleSheet("QPushButton{\n"
"    \n"
"    \n"
"    background-image: url(Casa.png);\n"
"   border-radius:15px;\n"
"   color:rgb(255, 255, 255)\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Beta/APP Beta/Versão Final App/exercicio/9ad3cf06-0eeb-47dc-ab27-6746152e15fb-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_casa.setIcon(icon8)
        self.btn_casa.setIconSize(QtCore.QSize(100, 100))
        self.btn_casa.setObjectName("btn_casa")
        self.verticalLayout_13.addWidget(self.btn_casa)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_3.setStyleSheet("background-color: #273C5E;\n"
"border-radius:15px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.btn_SeuTreino = QtWidgets.QPushButton(self.frame_3)
        self.btn_SeuTreino.setMinimumSize(QtCore.QSize(0, 400))
        self.btn_SeuTreino.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_SeuTreino.setFont(font)
        self.btn_SeuTreino.setStyleSheet("QPushButton{    \n"
"    \n"
"    background-image: url(SeuT.png);\n"
"   border-radius:15px;\n"
"   color:rgb(255, 255, 255)\n"
"\n"
"}")
        self.btn_SeuTreino.setIconSize(QtCore.QSize(0, 0))
        self.btn_SeuTreino.setObjectName("btn_SeuTreino")
        self.verticalLayout_12.addWidget(self.btn_SeuTreino)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout_11.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.PgTreino)
        self.PgConfiguracao = QtWidgets.QWidget()
        self.PgConfiguracao.setObjectName("PgConfiguracao")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.PgConfiguracao)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.frame_21 = QtWidgets.QFrame(self.PgConfiguracao)
        self.frame_21.setStyleSheet("background-color: #2D456B;\n"
"border-radius:15px;\n"
"color: rgb(255, 255, 255);")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.bttela = QtWidgets.QPushButton(self.frame_21)
        self.bttela.setMinimumSize(QtCore.QSize(0, 50))
        self.bttela.setStyleSheet("QPushButton:hover{\n"
"    background-color: #324D78;\n"
"   border-top-left-radus:15px\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Icons/Tamanho.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bttela.setIcon(icon9)
        self.bttela.setObjectName("bttela")
        self.verticalLayout_35.addWidget(self.bttela)
        self.bttema = QtWidgets.QPushButton(self.frame_21)
        self.bttema.setMinimumSize(QtCore.QSize(0, 50))
        self.bttema.setStyleSheet("QPushButton:hover{\n"
"    background-color: #324D78;\n"
"   border-top-left-radus:15px\n"
"}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Icons/Tema.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bttema.setIcon(icon10)
        self.bttema.setObjectName("bttema")
        self.verticalLayout_35.addWidget(self.bttema)
        self.btajuda = QtWidgets.QPushButton(self.frame_21)
        self.btajuda.setMinimumSize(QtCore.QSize(0, 50))
        self.btajuda.setStyleSheet("QPushButton:hover{\n"
"    background-color: #324D78;\n"
"   border-top-left-radus:15px\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Icons/Ajuda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btajuda.setIcon(icon11)
        self.btajuda.setObjectName("btajuda")
        self.verticalLayout_35.addWidget(self.btajuda)
        self.btacessivel = QtWidgets.QPushButton(self.frame_21)
        self.btacessivel.setMinimumSize(QtCore.QSize(0, 50))
        self.btacessivel.setStyleSheet("QPushButton:hover{\n"
"    background-color: #324D78;\n"
"   border-top-left-radus:15px\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Icons/Acessivel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btacessivel.setIcon(icon12)
        self.btacessivel.setObjectName("btacessivel")
        self.verticalLayout_35.addWidget(self.btacessivel)
        self.bttermos = QtWidgets.QPushButton(self.frame_21)
        self.bttermos.setMinimumSize(QtCore.QSize(0, 50))
        self.bttermos.setStyleSheet("QPushButton:hover{\n"
"    background-color: #324D78;\n"
"   border-top-left-radus:15px\n"
"}")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("Icons/uso.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bttermos.setIcon(icon13)
        self.bttermos.setObjectName("bttermos")
        self.verticalLayout_35.addWidget(self.bttermos)
        self.btlicenca = QtWidgets.QPushButton(self.frame_21)
        self.btlicenca.setMinimumSize(QtCore.QSize(0, 50))
        self.btlicenca.setStyleSheet("QPushButton:hover{\n"
"    background-color: #324D78;\n"
"   border-top-left-radus:15px\n"
"}")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("Icons/licensa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btlicenca.setIcon(icon14)
        self.btlicenca.setObjectName("btlicenca")
        self.verticalLayout_35.addWidget(self.btlicenca)
        self.verticalLayout_38.addWidget(self.frame_21)
        self.stackedWidget.addWidget(self.PgConfiguracao)
        self.PgAerobicos = QtWidgets.QWidget()
        self.PgAerobicos.setObjectName("PgAerobicos")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.PgAerobicos)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_14 = QtWidgets.QFrame(self.PgAerobicos)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.btn_voltarAero = QtWidgets.QPushButton(self.frame_14)
        self.btn_voltarAero.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_voltarAero.setStyleSheet("QPushButton{\n"
"background-color: #2D456B;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #324D78;\n"
"   border-top-left-radus:15px\n"
"}")
        self.btn_voltarAero.setText("")
        self.btn_voltarAero.setIcon(icon2)
        self.btn_voltarAero.setObjectName("btn_voltarAero")
        self.verticalLayout_27.addWidget(self.btn_voltarAero)
        self.scrollArea_6 = QtWidgets.QScrollArea(self.frame_14)
        self.scrollArea_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_9 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(0, 0, 732, 464))
        self.scrollAreaWidgetContents_9.setObjectName("scrollAreaWidgetContents_9")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_9)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_9)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_28.addWidget(self.label_13)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_9)
        self.label_12.setStyleSheet("")
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_28.addWidget(self.label_12)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_9)
        self.verticalLayout_27.addWidget(self.scrollArea_6)
        self.verticalLayout_26.addWidget(self.frame_14)
        self.stackedWidget.addWidget(self.PgAerobicos)
        self.PgCasa = QtWidgets.QWidget()
        self.PgCasa.setObjectName("PgCasa")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.PgCasa)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.btn_VoltarCasa = QtWidgets.QPushButton(self.PgCasa)
        self.btn_VoltarCasa.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_VoltarCasa.setStyleSheet("QPushButton{\n"
"background-color: #2D456B;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #324D78;\n"
"   border-top-left-radus:15px\n"
"}")
        self.btn_VoltarCasa.setText("")
        self.btn_VoltarCasa.setIcon(icon2)
        self.btn_VoltarCasa.setObjectName("btn_VoltarCasa")
        self.verticalLayout_14.addWidget(self.btn_VoltarCasa)
        self.frame_5 = QtWidgets.QFrame(self.PgCasa)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_5)
        self.scrollArea.setStyleSheet("color: rgb(0, 0, 0);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 278, 796))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_16.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_16.addWidget(self.label_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_15.addWidget(self.scrollArea)
        self.verticalLayout_14.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.PgCasa)
        self.PgAcademia = QtWidgets.QWidget()
        self.PgAcademia.setObjectName("PgAcademia")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.PgAcademia)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.btn_VoltarAcademia = QtWidgets.QPushButton(self.PgAcademia)
        self.btn_VoltarAcademia.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_VoltarAcademia.setStyleSheet("QPushButton{\n"
"background-color: #2D456B;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #324D78;\n"
"   border-top-left-radus:15px\n"
"}")
        self.btn_VoltarAcademia.setText("")
        self.btn_VoltarAcademia.setIcon(icon2)
        self.btn_VoltarAcademia.setObjectName("btn_VoltarAcademia")
        self.verticalLayout_17.addWidget(self.btn_VoltarAcademia)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.PgAcademia)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 328, 120))
        self.scrollAreaWidgetContents_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_18.addWidget(self.label_6)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents_3)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 296, 658))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_19.addWidget(self.label_5)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_18.addWidget(self.scrollArea_3)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_17.addWidget(self.scrollArea_2)
        self.stackedWidget.addWidget(self.PgAcademia)
        self.PgAlonga = QtWidgets.QWidget()
        self.PgAlonga.setObjectName("PgAlonga")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.PgAlonga)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.PgAlonga)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 367, 459))
        self.scrollAreaWidgetContents_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.btn_VoltarAlonga = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.btn_VoltarAlonga.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_VoltarAlonga.setStyleSheet("QPushButton{\n"
"background-color: #2D456B;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #324D78;\n"
"   border-top-left-radus:15px\n"
"}")
        self.btn_VoltarAlonga.setText("")
        self.btn_VoltarAlonga.setIcon(icon2)
        self.btn_VoltarAlonga.setObjectName("btn_VoltarAlonga")
        self.verticalLayout_21.addWidget(self.btn_VoltarAlonga)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_21.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_21.addWidget(self.label_7)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_20.addWidget(self.scrollArea_4)
        self.stackedWidget.addWidget(self.PgAlonga)
        self.PgSeuTreino = QtWidgets.QWidget()
        self.PgSeuTreino.setObjectName("PgSeuTreino")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.PgSeuTreino)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_6 = QtWidgets.QFrame(self.PgSeuTreino)
        self.frame_6.setStyleSheet("background-color: #273C5E;\n"
"border-radius:15px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_23 = QtWidgets.QLabel(self.frame_6)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_23.addWidget(self.label_23)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_7.setStyleSheet("background-color: #2D456B;\n"
"border-radius:15px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btvoltartreino = QtWidgets.QPushButton(self.frame_7)
        self.btvoltartreino.setMinimumSize(QtCore.QSize(0, 30))
        self.btvoltartreino.setStyleSheet("QPushButton{\n"
"background-color: #2D456B;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #324D78;\n"
"   border-top-left-radus:15px\n"
"}")
        self.btvoltartreino.setText("")
        self.btvoltartreino.setIcon(icon2)
        self.btvoltartreino.setObjectName("btvoltartreino")
        self.horizontalLayout_5.addWidget(self.btvoltartreino)
        self.bteditartreino = QtWidgets.QPushButton(self.frame_7)
        self.bteditartreino.setMinimumSize(QtCore.QSize(0, 30))
        self.bteditartreino.setStyleSheet("QPushButton{\n"
"background-color: #2D456B;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #324D78;\n"
"   border-top-left-radus:15px\n"
"}")
        self.bteditartreino.setText("")
        self.bteditartreino.setIcon(icon3)
        self.bteditartreino.setObjectName("bteditartreino")
        self.horizontalLayout_5.addWidget(self.bteditartreino)
        self.btsalvartreino = QtWidgets.QPushButton(self.frame_7)
        self.btsalvartreino.setMinimumSize(QtCore.QSize(0, 30))
        self.btsalvartreino.setStyleSheet("QPushButton{\n"
"background-color: #2D456B;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #324D78;\n"
"   border-top-left-radus:15px\n"
"}")
        self.btsalvartreino.setText("")
        self.btsalvartreino.setIcon(icon4)
        self.btsalvartreino.setObjectName("btsalvartreino")
        self.horizontalLayout_5.addWidget(self.btsalvartreino)
        self.verticalLayout_23.addWidget(self.frame_7)
        self.Menutreinar = QtWidgets.QFrame(self.frame_6)
        self.Menutreinar.setMinimumSize(QtCore.QSize(0, 0))
        self.Menutreinar.setMaximumSize(QtCore.QSize(16777215, 0))
        self.Menutreinar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Menutreinar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Menutreinar.setObjectName("Menutreinar")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.Menutreinar)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.scrollArea_7 = QtWidgets.QScrollArea(self.Menutreinar)
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 714, 174))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_7)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_23 = QtWidgets.QFrame(self.scrollAreaWidgetContents_7)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_45 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.label_16 = QtWidgets.QLabel(self.frame_23)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_45.addWidget(self.label_16)
        self.comboBox = QtWidgets.QComboBox(self.frame_23)
        self.comboBox.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"border-color: rgb(136, 138, 133);")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_45.addWidget(self.comboBox)
        self.label_14 = QtWidgets.QLabel(self.frame_23)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_45.addWidget(self.label_14)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_23)
        self.comboBox_2.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"border-color: rgb(136, 138, 133);\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_45.addWidget(self.comboBox_2)
        self.label_15 = QtWidgets.QLabel(self.frame_23)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_45.addWidget(self.label_15)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_23)
        self.comboBox_3.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"border-color: rgb(136, 138, 133);\n"
"")
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout_45.addWidget(self.comboBox_3)
        self.horizontalLayout_11.addWidget(self.frame_23)
        self.frame_24 = QtWidgets.QFrame(self.scrollAreaWidgetContents_7)
        self.frame_24.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.ImagemTreino = QtWidgets.QLabel(self.frame_24)
        self.ImagemTreino.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ImagemTreino.setText("")
        self.ImagemTreino.setAlignment(QtCore.Qt.AlignCenter)
        self.ImagemTreino.setWordWrap(True)
        self.ImagemTreino.setObjectName("ImagemTreino")
        self.verticalLayout_46.addWidget(self.ImagemTreino)
        self.horizontalLayout_11.addWidget(self.frame_24)
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_7)
        self.verticalLayout_41.addWidget(self.scrollArea_7)
        self.verticalLayout_23.addWidget(self.Menutreinar)
        self.scrollArea_5 = QtWidgets.QScrollArea(self.frame_6)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 746, 405))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_6)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.frame_40 = QtWidgets.QFrame(self.scrollAreaWidgetContents_6)
        self.frame_40.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 255, 255);")
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_40)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_41 = QtWidgets.QFrame(self.frame_40)
        self.frame_41.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.verticalLayout_56 = QtWidgets.QVBoxLayout(self.frame_41)
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.Exercicios_foto1 = QtWidgets.QLabel(self.frame_41)
        self.Exercicios_foto1.setText("")
        self.Exercicios_foto1.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_foto1.setObjectName("Exercicios_foto1")
        self.verticalLayout_56.addWidget(self.Exercicios_foto1)
        self.Exercicios_list1 = QtWidgets.QLabel(self.frame_41)
        self.Exercicios_list1.setText("")
        self.Exercicios_list1.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_list1.setObjectName("Exercicios_list1")
        self.verticalLayout_56.addWidget(self.Exercicios_list1)
        self.gridLayout_3.addWidget(self.frame_41, 0, 0, 1, 1)
        self.frame_42 = QtWidgets.QFrame(self.frame_40)
        self.frame_42.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.verticalLayout_57 = QtWidgets.QVBoxLayout(self.frame_42)
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.Exercicios_foto2 = QtWidgets.QLabel(self.frame_42)
        self.Exercicios_foto2.setText("")
        self.Exercicios_foto2.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_foto2.setObjectName("Exercicios_foto2")
        self.verticalLayout_57.addWidget(self.Exercicios_foto2)
        self.Exercicios_list2 = QtWidgets.QLabel(self.frame_42)
        self.Exercicios_list2.setText("")
        self.Exercicios_list2.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_list2.setObjectName("Exercicios_list2")
        self.verticalLayout_57.addWidget(self.Exercicios_list2)
        self.gridLayout_3.addWidget(self.frame_42, 0, 1, 1, 1)
        self.frame_45 = QtWidgets.QFrame(self.frame_40)
        self.frame_45.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.verticalLayout_58 = QtWidgets.QVBoxLayout(self.frame_45)
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.Exercicios_foto3 = QtWidgets.QLabel(self.frame_45)
        self.Exercicios_foto3.setText("")
        self.Exercicios_foto3.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_foto3.setObjectName("Exercicios_foto3")
        self.verticalLayout_58.addWidget(self.Exercicios_foto3)
        self.Exercicios_list3 = QtWidgets.QLabel(self.frame_45)
        self.Exercicios_list3.setText("")
        self.Exercicios_list3.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_list3.setObjectName("Exercicios_list3")
        self.verticalLayout_58.addWidget(self.Exercicios_list3)
        self.gridLayout_3.addWidget(self.frame_45, 0, 2, 1, 1)
        self.frame_44 = QtWidgets.QFrame(self.frame_40)
        self.frame_44.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.verticalLayout_59 = QtWidgets.QVBoxLayout(self.frame_44)
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.Exercicios_foto4 = QtWidgets.QLabel(self.frame_44)
        self.Exercicios_foto4.setText("")
        self.Exercicios_foto4.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_foto4.setObjectName("Exercicios_foto4")
        self.verticalLayout_59.addWidget(self.Exercicios_foto4)
        self.Exercicios_list4 = QtWidgets.QLabel(self.frame_44)
        self.Exercicios_list4.setText("")
        self.Exercicios_list4.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_list4.setObjectName("Exercicios_list4")
        self.verticalLayout_59.addWidget(self.Exercicios_list4)
        self.gridLayout_3.addWidget(self.frame_44, 1, 0, 1, 1)
        self.frame_47 = QtWidgets.QFrame(self.frame_40)
        self.frame_47.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.frame_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.verticalLayout_60 = QtWidgets.QVBoxLayout(self.frame_47)
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.Exercicios_foto5 = QtWidgets.QLabel(self.frame_47)
        self.Exercicios_foto5.setText("")
        self.Exercicios_foto5.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_foto5.setObjectName("Exercicios_foto5")
        self.verticalLayout_60.addWidget(self.Exercicios_foto5)
        self.Exercicios_list5 = QtWidgets.QLabel(self.frame_47)
        self.Exercicios_list5.setText("")
        self.Exercicios_list5.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_list5.setObjectName("Exercicios_list5")
        self.verticalLayout_60.addWidget(self.Exercicios_list5)
        self.gridLayout_3.addWidget(self.frame_47, 1, 1, 1, 1)
        self.frame_49 = QtWidgets.QFrame(self.frame_40)
        self.frame_49.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.frame_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_49.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_49.setObjectName("frame_49")
        self.verticalLayout_61 = QtWidgets.QVBoxLayout(self.frame_49)
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self.Exercicios_foto6 = QtWidgets.QLabel(self.frame_49)
        self.Exercicios_foto6.setText("")
        self.Exercicios_foto6.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_foto6.setObjectName("Exercicios_foto6")
        self.verticalLayout_61.addWidget(self.Exercicios_foto6)
        self.Exercicios_list6 = QtWidgets.QLabel(self.frame_49)
        self.Exercicios_list6.setText("")
        self.Exercicios_list6.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_list6.setObjectName("Exercicios_list6")
        self.verticalLayout_61.addWidget(self.Exercicios_list6)
        self.gridLayout_3.addWidget(self.frame_49, 1, 2, 1, 1)
        self.frame_43 = QtWidgets.QFrame(self.frame_40)
        self.frame_43.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.verticalLayout_62 = QtWidgets.QVBoxLayout(self.frame_43)
        self.verticalLayout_62.setObjectName("verticalLayout_62")
        self.Exercicios_foto7 = QtWidgets.QLabel(self.frame_43)
        self.Exercicios_foto7.setText("")
        self.Exercicios_foto7.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_foto7.setObjectName("Exercicios_foto7")
        self.verticalLayout_62.addWidget(self.Exercicios_foto7)
        self.Exercicios_list7 = QtWidgets.QLabel(self.frame_43)
        self.Exercicios_list7.setText("")
        self.Exercicios_list7.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_list7.setObjectName("Exercicios_list7")
        self.verticalLayout_62.addWidget(self.Exercicios_list7)
        self.gridLayout_3.addWidget(self.frame_43, 2, 0, 1, 1)
        self.frame_48 = QtWidgets.QFrame(self.frame_40)
        self.frame_48.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.frame_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.verticalLayout_63 = QtWidgets.QVBoxLayout(self.frame_48)
        self.verticalLayout_63.setObjectName("verticalLayout_63")
        self.Exercicios_foto8 = QtWidgets.QLabel(self.frame_48)
        self.Exercicios_foto8.setText("")
        self.Exercicios_foto8.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_foto8.setObjectName("Exercicios_foto8")
        self.verticalLayout_63.addWidget(self.Exercicios_foto8)
        self.Exercicios_list8 = QtWidgets.QLabel(self.frame_48)
        self.Exercicios_list8.setText("")
        self.Exercicios_list8.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_list8.setObjectName("Exercicios_list8")
        self.verticalLayout_63.addWidget(self.Exercicios_list8)
        self.gridLayout_3.addWidget(self.frame_48, 2, 1, 1, 1)
        self.frame_46 = QtWidgets.QFrame(self.frame_40)
        self.frame_46.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.verticalLayout_64 = QtWidgets.QVBoxLayout(self.frame_46)
        self.verticalLayout_64.setObjectName("verticalLayout_64")
        self.Exercicios_foto9 = QtWidgets.QLabel(self.frame_46)
        self.Exercicios_foto9.setText("")
        self.Exercicios_foto9.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_foto9.setObjectName("Exercicios_foto9")
        self.verticalLayout_64.addWidget(self.Exercicios_foto9)
        self.Exercicios_list9 = QtWidgets.QLabel(self.frame_46)
        self.Exercicios_list9.setText("")
        self.Exercicios_list9.setAlignment(QtCore.Qt.AlignCenter)
        self.Exercicios_list9.setObjectName("Exercicios_list9")
        self.verticalLayout_64.addWidget(self.Exercicios_list9)
        self.gridLayout_3.addWidget(self.frame_46, 2, 2, 1, 1)
        self.verticalLayout_40.addWidget(self.frame_40)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_6)
        self.verticalLayout_23.addWidget(self.scrollArea_5)
        self.verticalLayout_22.addWidget(self.frame_6)
        self.stackedWidget.addWidget(self.PgSeuTreino)
        self.horizontalLayout_4.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.MainFrame)
        self.FooterFrame = QtWidgets.QFrame(self.Main)
        self.FooterFrame.setStyleSheet("")
        self.FooterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FooterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FooterFrame.setObjectName("FooterFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.FooterFrame)
        self.horizontalLayout_2.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.FooterFrame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.FooterFrame)
        self.gridLayout.addWidget(self.Main, 0, 1, 1, 1)
        self.Left = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Left.sizePolicy().hasHeightForWidth())
        self.Left.setSizePolicy(sizePolicy)
        self.Left.setMinimumSize(QtCore.QSize(0, 0))
        self.Left.setMaximumSize(QtCore.QSize(9, 16777215))
        self.Left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Left.setObjectName("Left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Left)
        self.verticalLayout_2.setContentsMargins(-1, 9, 0, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Frameapp = QtWidgets.QFrame(self.Left)
        self.Frameapp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frameapp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frameapp.setObjectName("Frameapp")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Frameapp)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LabelNomeapp = QtWidgets.QLabel(self.Frameapp)
        self.LabelNomeapp.setObjectName("LabelNomeapp")
        self.verticalLayout_3.addWidget(self.LabelNomeapp)
        self.verticalLayout_2.addWidget(self.Frameapp)
        self.Framemenu = QtWidgets.QFrame(self.Left)
        self.Framemenu.setStyleSheet("QFrame{\n"
"    background-color: #223452\n"
"}\n"
"\n"
"QToolBox{\n"
"    text-algn:left;\n"
"    background-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QToolBox::tab{\n"
"    border-radius: Spx;\n"
"    background-color:#223452;\n"
"     text-algn:left;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Framemenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Framemenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Framemenu.setObjectName("Framemenu")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Framemenu)
        self.verticalLayout_6.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.toolBoxmenu = QtWidgets.QToolBox(self.Framemenu)
        self.toolBoxmenu.setMinimumSize(QtCore.QSize(180, 0))
        self.toolBoxmenu.setStyleSheet("QPushButton:hover{\n"
"    background-color: #324D78;\n"
"   border-top-left-radus:15px\n"
"}\n"
"\n"
"QPushButton{\n"
"   color:rgb(255, 255, 255);\n"
"    background-color: #2D456B;\n"
"}")
        self.toolBoxmenu.setObjectName("toolBoxmenu")
        self.menu = QtWidgets.QWidget()
        self.menu.setGeometry(QtCore.QRect(0, 0, 180, 527))
        self.menu.setObjectName("menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_Home = QtWidgets.QPushButton(self.menu)
        self.btn_Home.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_Home.setSizeIncrement(QtCore.QSize(0, 0))
        self.btn_Home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("Icons/Home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Home.setIcon(icon15)
        self.btn_Home.setObjectName("btn_Home")
        self.verticalLayout_4.addWidget(self.btn_Home)
        self.btn_Config = QtWidgets.QPushButton(self.menu)
        self.btn_Config.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_Config.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("Icons/Configuracao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Config.setIcon(icon16)
        self.btn_Config.setObjectName("btn_Config")
        self.verticalLayout_4.addWidget(self.btn_Config)
        self.btn_Lembrete = QtWidgets.QPushButton(self.menu)
        self.btn_Lembrete.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_Lembrete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("Icons/Alarme.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Lembrete.setIcon(icon17)
        self.btn_Lembrete.setObjectName("btn_Lembrete")
        self.verticalLayout_4.addWidget(self.btn_Lembrete)
        self.btn_relatorio = QtWidgets.QPushButton(self.menu)
        self.btn_relatorio.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_relatorio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("Icons/Relatorio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_relatorio.setIcon(icon18)
        self.btn_relatorio.setObjectName("btn_relatorio")
        self.verticalLayout_4.addWidget(self.btn_relatorio)
        self.btn_Dieta = QtWidgets.QPushButton(self.menu)
        self.btn_Dieta.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_Dieta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("Icons/Alimentacao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Dieta.setIcon(icon19)
        self.btn_Dieta.setObjectName("btn_Dieta")
        self.verticalLayout_4.addWidget(self.btn_Dieta)
        self.btn_chat = QtWidgets.QPushButton(self.menu)
        self.btn_chat.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_chat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_chat.setIcon(icon5)
        self.btn_chat.setObjectName("btn_chat")
        self.verticalLayout_4.addWidget(self.btn_chat)
        self.btn_Perfil = QtWidgets.QPushButton(self.menu)
        self.btn_Perfil.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_Perfil.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("Icons/Perfil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Perfil.setIcon(icon20)
        self.btn_Perfil.setObjectName("btn_Perfil")
        self.verticalLayout_4.addWidget(self.btn_Perfil)
        self.btn_treino = QtWidgets.QPushButton(self.menu)
        self.btn_treino.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_treino.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("Icons/Treino.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_treino.setIcon(icon21)
        self.btn_treino.setObjectName("btn_treino")
        self.verticalLayout_4.addWidget(self.btn_treino)
        self.btn_Sair = QtWidgets.QPushButton(self.menu)
        self.btn_Sair.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_Sair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Sair.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("Icons/Sair.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Sair.setIcon(icon22)
        self.btn_Sair.setObjectName("btn_Sair")
        self.verticalLayout_4.addWidget(self.btn_Sair)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.toolBoxmenu.addItem(self.menu, "")
        self.Info = QtWidgets.QWidget()
        self.Info.setGeometry(QtCore.QRect(0, 0, 180, 527))
        self.Info.setStyleSheet("")
        self.Info.setObjectName("Info")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Info)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_9 = QtWidgets.QFrame(self.Info)
        self.frame_9.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_11 = QtWidgets.QLabel(self.frame_9)
        self.label_11.setGeometry(QtCore.QRect(0, 40, 161, 161))
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.frame_9)
        self.toolBoxmenu.addItem(self.Info, "")
        self.verticalLayout_6.addWidget(self.toolBoxmenu)
        self.verticalLayout_2.addWidget(self.Framemenu)
        self.gridLayout.addWidget(self.Left, 0, 0, 1, 1)
        MainWindow2.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow2)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.toolBoxmenu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TopFrame.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">OCM  - Oficina do Corpo em Movimento</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Username</p></body></html>"))
        self.Labelnome.setText(_translate("MainWindow", "Nome:"))
        self.Labelemail.setText(_translate("MainWindow", "Email:"))
        self.Labeltelefone.setText(_translate("MainWindow", "Telefone:"))
        self.mudarsenha.setText(_translate("MainWindow", "Mudar senha"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Informações"))
        self.Labelpeso.setText(_translate("MainWindow", "Peso:"))
        self.LabelAltura.setText(_translate("MainWindow", "Altura:"))
        self.LabelImc.setText(_translate("MainWindow", "IMC:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Ficha"))
        self.btn_editarUser.setText(_translate("MainWindow", "Editar"))
        self.btn_Alterconta.setText(_translate("MainWindow", "Alterar Conta"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p>Total</p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "Sua Alimentação"))
        self.label_19.setText(_translate("MainWindow", "Refeição"))
        self.label_21.setText(_translate("MainWindow", "Horário"))
        self.label_28.setText(_translate("MainWindow", "Preescrição"))
        self.label_25.setText(_translate("MainWindow", "De:"))
        self.label_26.setText(_translate("MainWindow", "Para:"))
        self.label_27.setText(_translate("MainWindow", "Assunto:"))
        self.label_24.setText(_translate("MainWindow", "Mensagem:"))
        self.pushButton_2.setText(_translate("MainWindow", "Enviar"))
        self.btn_Anae.setText(_translate("MainWindow", "Aeróbicos"))
        self.btn_academia.setText(_translate("MainWindow", "Academia"))
        self.btn_Alonga.setText(_translate("MainWindow", "Alongamento"))
        self.btn_casa.setText(_translate("MainWindow", "Casa"))
        self.btn_SeuTreino.setText(_translate("MainWindow", "Seu Treino"))
        self.bttela.setText(_translate("MainWindow", "Resolução"))
        self.bttema.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/Icons/Icons/Linguagem.png\"/><span style=\" font-size:14pt;\">Idioma</span></p></body></html>"))
        self.bttema.setText(_translate("MainWindow", "Temas"))
        self.btajuda.setText(_translate("MainWindow", "Suporte"))
        self.btacessivel.setText(_translate("MainWindow", "Acessibilidade"))
        self.bttermos.setText(_translate("MainWindow", "Termos de uso"))
        self.btlicenca.setText(_translate("MainWindow", "Licença"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; font-style:italic;\">Guia de Treino Aeróbicos</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>Estes exercícios são exercícios complexos. Recrutam múltiplas articulações e mais de um grupo muscular. Eles melhoram a coordenação e elevam a frequência cardíaca mais rapidamente. Além disso, permitem que uma pessoa faça um treino de corpo inteiro em menos tempo e imite os movimentos da vida real. Um treino HIIT de alto impacto como este também queima mais calorias do que um treino cardiovascular lento e estável. </p><p><br/></p><p>Então, procure fazer os exercícios aeróbicos duas a três vezes por semana. Se você for iniciante nesse tipo de treino, perceberá que as mudanças acontecem rapidamente. Normalmente, leva cerca de três a quatro semanas para o corpo de alguém ajustar-se ao treinamento para que os resultados melhorem. Com o tempo, você pode perder peso e ganhar força. </p><p><br/></p><p>Você pode fazer um circuito de 20 minutos com os melhores exercícios aeróbicos. É recomendado escolher de seis a oito deles e descansar por 30 segundos entre cada um. Você sentirá seu coração começar acelerar e os benefícios aparecerem.</p><p><span style=\" color:#ffffff;\"><br/></span></p><p><span style=\" color:#ffffff;\"><br/></span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; font-style:italic;\">Guia de Treino em Casa</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Separe um espaço: </span>pode ser a sala, o quarto, o quintal… O importante é tirar objetos que aumentam o risco de acidentes. Cuidado com pisos escorregadios e tapetes.</p><p><br/></p><p><span style=\" font-weight:600;\">Converse com um especialista:</span> quem tem personal trainer ou ia à academia deve manter o contato para ajustar o exercício.</p><p><br/></p><p><span style=\" font-weight:600;\">Estabeleça uma rotina:</span> “Reserve dias e horários específicos para a atividade física” </p><p><br/></p><p><span style=\" font-weight:600;\">Monitore seu treino:</span> aplicativos são uma boa forma de verificar sua adesão a uma rotina ativa durante o isolamento social. Observar a evolução gera motivação. </p><p><br/></p><p><span style=\" font-weight:600;\">Faça um aquecimento: </span>simule, em ritmo lento, gestos básicos que serão executados antes de começar pra valer. Isso minimiza a probabilidade de lesões incômodas.</p><p><br/></p><p><br/></p><p><br/></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; font-style:italic;\">Guia de Treino na Academia</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">A ordem e o esforço:</span> veja a sequência toda antes de iniciar, porque o descanso entre uma atividade e outra é curto. Depois de dar uma nota de 0 a 10 sobre o esforço exigido, procure chegar a 7. Se estiver bem, acelere um pouco. </p><p><br/></p><p><span style=\" font-weight:600;\">O tempo:</span> todo exercício deve perdurar por 30 segundos. “Esse ritmo ajuda a manter a concentração e uma frequência cardíaca elevada”.</p><p><br/></p><p><span style=\" font-weight:600;\">O descanso:</span> pare por dez segundos enquanto já se prepara para o item seguinte da sessão. Pessoas com hipertensão devem ampliar esse período de repouso para a pressão baixar um pouco. </p><p><br/></p><p><span style=\" font-weight:600;\">A sessão:</span> cada sequência completa vai durar oito minutos — ou um pouco mais, a depender da velocidade na hora de passar de uma atividade para outra. Aí pare até recuperar o fôlego e repita mais duas vezes.</p><p><br/></p><p><br/></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; font-style:italic;\">Guia de Treino no Alongamento</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Fazer um bom alongamento aumenta a flexibilidade e reduz os riscos de lesões durante o treino e no dia a dia. Se você não tem experiência, comece com alguns movimentos básicos para aquecer os músculos — antes e depois de praticar exercícios, mesmo que seja uma caminhada simples. Quanto à frequência, o ideal é se alongar todos os dias, mas uma frequência de três a quatro vezes por semana já está de bom tamanho. Por fim, quem tem mais experiência pode alongar partes específicas do corpo.</p><p><br/></p><p><br/></p><p><br/></p><p><br/></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Seu Treino</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "Exercícios"))
        self.label_14.setText(_translate("MainWindow", "Séries"))
        self.label_15.setText(_translate("MainWindow", "Repetições"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">©</span><span style=\" font-size:12pt;\">Orange Tech</span></p></body></html>"))
        self.LabelNomeapp.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">OCM</span></p></body></html>"))
        self.btn_Home.setText(_translate("MainWindow", " Home"))
        self.btn_Config.setText(_translate("MainWindow", " Configuração"))
        self.btn_Lembrete.setText(_translate("MainWindow", " Lembrete"))
        self.btn_relatorio.setText(_translate("MainWindow", " Relatório"))
        self.btn_Dieta.setText(_translate("MainWindow", " Dieta"))
        self.btn_chat.setText(_translate("MainWindow", "Mensagem"))
        self.btn_Perfil.setText(_translate("MainWindow", " Perfil"))
        self.btn_treino.setText(_translate("MainWindow", " Treino"))
        self.toolBoxmenu.setItemText(self.toolBoxmenu.indexOf(self.menu), _translate("MainWindow", "início"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">Criador: Orange Tech</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">Parceria: SESI SENAI</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">Cliente: Professora Kivia</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">Instrutor: Thiago Macklin</span></p></body></html>"))
        self.toolBoxmenu.setItemText(self.toolBoxmenu.indexOf(self.Info), _translate("MainWindow", "Informações"))
import Front_End.Imagem as Imagem
